### ISSUE TITLE
G2 preview is incorrect

### ISSUE THREAD

**Issue by machinekoder** [qtquickvcp/QtQuickVcp#11]
Previews of the G2 GCode are incorrect sometimes

**Comment by strahlex** [comment]
This should be fixed now.

**Comment by ArcEye** [comment]
G1 moves are now shown in their entirety in some programs but not others.
Test1
The program square5.ngc
'''
G40 G90
G54
G21 G17
G8

S600 M3

G00 X0 Y0
G00 Z5.000000

G00 X10 Y22.5

G01 Z-0.125000 F100
G01 X22.5 Y22.5 F400
G01 X22.5 Y10 
G01 X10 Y10
G01 X10 Y22.5 
G01 X22.5 Y10
G00 Z5

M5
G00 X0.0000 Y0.0000
M2
'''
All the lines of movement are drawn in preview and when run, the current line is highlighted bright
red and the movement trace remains in dull red.

Test2
However the test program I posted above, movetest_mill_4.ngc,  still only shows the first 2 G1 moves in preview
When run it completes the program, but does not leave a trace plot to show the path it has taken. 

Test3
A test program consisting of largely G3 moves, spiral3.ngc
'''
G40 G90
G20 G17
G40 G8
F3000
G00 X0.7500 Y0.7700
G01 Z-0.0300
G03X0.7000Y0.7200I0.0000J-0.0500
X0.7500Y0.6700I0.0500J0.0000
X0.8300Y0.7500I0.0000J0.0800
X0.7500Y0.8300I-0.0800J0.0000
X0.6400Y0.7200I0.0000J-0.1100
X0.7500Y0.6100I0.1100J0.0000
X0.8900Y0.7500I0.0000J0.1400
X0.7500Y0.8900I-0.1400J0.0000
X0.5800Y0.7200I0.0000J-0.1700
X0.7500Y0.5500I0.1700J0.0000
X0.9500Y0.7500I0.0000J0.2000
X0.7500Y0.9500I-0.2000J0.0000
X0.5200Y0.7200I0.0000J-0.2300
X0.7500Y0.4900I0.2300J0.0000
X1.0100Y0.7500I0.0000J0.2600
X0.7500Y1.0100I-0.2600J0.0000
X0.4600Y0.7200I0.0000J-0.2900
X0.7500Y0.4300I0.2900J0.0000
X1.0700Y0.7500I0.0000J0.3200
X0.7500Y1.0700I-0.3200J0.0000
X0.4000Y0.7200I0.0000J-0.3500
X0.7500Y0.3700I0.3500J0.0000
X1.1300Y0.7500I0.0000J0.3800
X0.7500Y1.1300I-0.3800J0.0000
X0.3400Y0.7200I0.0000J-0.4100
X0.7500Y0.3100I0.4100J0.0000
X1.1900Y0.7500I0.0000J0.4400
X0.7500Y1.1900I-0.4400J0.0000
X0.3100Y0.7500I0.0000J-0.4400
X0.7362Y0.3102I0.4400J0.0000
G00Z0.1500
G00X0.0Y0.0
G28
M2
'''
This previews and runs as expected.

The only difference I can see, is that when the preview interpreter hits a M6Tx command
it stops producing any preview plot ?

**Comment by strahlex** [comment]
Is this still a problem?
