### ISSUE TITLE
Reopen Current File Problem

### ISSUE THREAD

**Issue by nikunjanand456** [qtquickvcp/QtQuickVcp#116]
Reopening of File Not Working 

If i edited ngc file and after reload it again it not showing latest file

but if i am loading other file and loading same file then its working

**Comment by machinekoder** [comment]
I can confirm this problem. To solve the problem, this would require some hash served with the file to know that there have been changes.

**Comment by machinekoder** [comment]
@nikunjanand456 The remote file editing support should solve your problem.
