### ISSUE TITLE
Stable Windows Releases do not work at all

### ISSUE THREAD

**Issue by RicoKirstein** [qtquickvcp/QtQuickVcp#160]
The x64 and x86 Stable Releases for Windows both are named x64 on the download button and both don't work.
They start up to a grey screen saying loading in the title bar.
![image](https://cloud.githubusercontent.com/assets/1696635/24586543/48896308-17a4-11e7-8aca-a39dee49454b.png)

**Comment by machinekoder** [comment]
Good point. I should remove the stable release for now since they are not updated regularly.
