### ISSUE TITLE
Disable application output remote UI

### ISSUE THREAD

**Issue by luminize** [qtquickvcp/QtQuickVcp#167]
I've made a UI and compiled it, then start it from a python program with `launcher.start_process('~/path/to/application -W')

All output is shown in the terminal. (any terminal for that matter) Can I disable that somehow?

**Comment by machinekoder** [comment]
Yes, compile it in release mode (QtQuickVcp + the UI).

**Comment by machinekoder** [comment]
If there is still some debug output left you can pipe it somewhere else: `foo > bar.log`

**Comment by luminize** [comment]
That doesn't seem to solve it. Still as much output as before.
Maybe I erred and it's not debug messages. Anyway these output (and much more) I see:
```
[ SD ] trying to open network session
[ SD ] number of configs:  3
[ SD ] network config:  "Ethernet" 1 "Wired connection 1"
[ SD ] "Initializing JDNS multicast"
[ SD ] Started query 1 "_config._sub._machinekit._tcp.local" 12
[ SD ] Started query 2 "_launcher._sub._machinekit._tcp.local" 12
...
...
[ "Remote Component Base" ] Event CONNECT
[ "Remote Component Base" ] State TRYING
[ "tubeturner" ] pin added:  "en_recipy"
[ "tubeturner" ] pin added:  "cbo_recipy"
[ "tubeturner" ] pin added:  "en_enter"
...
...
[ "Remote Component Base - halrcmd" ] Event HEARTBEAT TICK
[ "Remote Component Base - halrcmd" ] sent message "type: MT_PING\n"
[ "Remote Component Base - halrcmd" ] Event ANY MSG SENT
[ "Remote Component Base - halrcmd" ] server message "type: MT_PING_ACKNOWLEDGE\nuuid: \"(RG\\250;\\034\\021\\347\\253\\231\\000\\037)\\000\\354o\"\n"
[ "Remote Component Base - halrcmd" ] Event ANY MSG RECEIVED
...
...
```

**Comment by machinekoder** [comment]
Make sure you **Rebuild** the QtQuickVcp project.

**Comment by luminize** [comment]
yes, I put in release mode, then rebuild, (CTRL+B)
after that run (CTRL+R) the app and you'll see also output in the application output window (3) at the bottom in the Qt environment.

**Comment by machinekoder** [comment]
`make install` was run? Because the application uses QtQuickVcp from the install path.
![image](https://cloud.githubusercontent.com/assets/1467368/26198367/0c36f9ba-3bc6-11e7-883e-58d78c2b1355.png)

**Comment by luminize** [comment]
apologies, I compiled only the UI in release mode. Compiling QtQuickVCP in release mode solved the problem.
Thanks @machinekoder
