### ISSUE TITLE
Bintray Account has been rate limited

### ISSUE THREAD

**Issue by machinekoder** [qtquickvcp/QtQuickVcp#173]
Downloads are currently impossible since we hit the rate limit in Bintray. 10GB of data or 10TB or up/downloads - I suspect the binary builds should be cleaned from time to time.

**Comment by spaivaras** [comment]
Any way to temporally place stable builds somewhere else? like dropbox?

**Comment by machinekoder** [comment]
The problem has been fixed and the account is re-enabled. Btw. I dropped the stable releases since maintaining them is an unnecessary effort. The master branch should be stable anyways.
