### ISSUE TITLE
gcode program preview doesn't move after touch off

### ISSUE THREAD

**Issue by machinekoder** [qtquickvcp/QtQuickVcp#219]
Moved from: https://github.com/qtquickvcp/Cetus/issues/7

After loading any ngc file, live preview is probably set to 0,0 machine coordinates. And doesn't move when doing touch off on any axis (coordinate origin is moved tho). While doing same operation in axis GUI coordinate origin is moved to current tool location and preview is moved related to touched off position. Is this intended or a bug in preview?Client tested on all OS'es: OSX sierra, windows 10 64bit, ubuntu 16.04 64bitmachinekit running on debian jessie

**Comment by machinekoder** [comment]
@spaivaras This behavior is not intended. Instead, the preview should be refreshed after a touch of operation or the preview of offset updated - whatever is more applicable.

**Comment by spaivaras** [comment]
I am looking into this myself but my qt knowledge is very basic. It seems that after touch off no updates are called to GLPathItem::calculateNewPosition which seems to be handling g5x offsets. If I will find anything usefull will post here
