### ISSUE TITLE
PathView3D drawing error for G3

### ISSUE THREAD

**Issue by f1oat** [qtquickvcp/QtQuickVcp#37]
Here is a simple test sequence showing the issue on G3.

**G21 G90 G64 G40
G17
F100
G0 X0 Y0
G91
M3 S1000
G1 X0 Y0
G2 X10 Y10 I10
G3 X10 Y-10 I10
M5
M2**

Result with Axis: 
![Axis result](http://snag.gy/9lr7a.jpg)
Result with PathView3D: 
![PathView3D result](http://snag.gy/e0S4I.jpg)

Pathview3D is drawing "G3 X10 **Y-10** I10" as if it was "G3 X10 **Y+10** I10"

**Comment by strahlex** [comment]
The relevant code is here: https://github.com/strahlex/QtQuickVcp/blob/master/src/pathview/qglpathitem.cpp#L482

**Comment by strahlex** [comment]
fixed by https://github.com/strahlex/QtQuickVcp/commit/88a7a019507bb92aa3604d83531a32c253af0618

**Comment by strahlex** [comment]
can we close this?

**Comment by f1oat** [comment]
I have to check with up to date repo.
As far as I remember, there were a graphical glitch on another portion 
of the drawing.
