### ISSUE TITLE
Key Event Not Working in Any shortcuts

### ISSUE THREAD

**Issue by ankit8611** [qtquickvcp/QtQuickVcp#52]
Hello Strahlex
In Machineface or Cetus Key events not Working 
And if working how use tell me about the key Events

Like Machine's X-axis direction working on UpArrow Key And DownArrow Key 
Y-axis direction on LeftArrow Key and RightArrow Key
Z-axis direction on PageUp Key and PageDown Key like Axis GUI
so How it works please 
tell me Sir.....

Any Idea

**Comment by koppi** [comment]
I have the same issue on Ubuntu 16.04 with the sock window manager.

**Comment by strahlex** [comment]
QtQuick's key event handling is bit more complicated http://doc.qt.io/qt-5/qtquick-input-focus.html and depends on the current focus. Not sure how different window managers relate to the problem.

Arrow-keys are in general not implemented by QtQuickVcp components.

**Comment by machinekoder** [comment]
@ankit8611 I recently added keyboard jogging to Cetus.

**Comment by machinekoder** [comment]
Jogging the axes with the arrow keys should work now.
